services:
  - type: web
    name: aerotrack
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: aerotrack.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://aerotrack.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: aerotrack-db
          property: connectionString

databases:
  - name: aerotrack-db
    databaseName: aerotrack_db
    user: aerotrack_user
